trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://$(PAT)@github.com/JulliaPatrocinio/BackupRepo.git
    tar -czf backup.tar.gz BackupRepo
    az storage blob upload --container-name backups --file backup.tar.gz --name backup.tar.gz
  displayName: 'Backup repository'
